baseurl="https://blog.webfuns.net"
languageCode = "en-us"
title="趣味互联网"
Paginate=10
PaginatePath="page"
#[permalinks]
#  post= "/:year/:month-:day"
[params]
  SubTitle= "她简单到只有0和1，却丰富了整个世界。"
  AuthorName= "Tom Heng"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
